version: '3.8'

services:
  serasa-brain-ag-challenge-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${TYPEORM_HOST}
      - DB_PORT=${TYPEORM_PORT}
      - DB_USER=${TYPEORM_USERNAME}
      - DB_PASS=${TYPEORM_PASSWORD}
      - DB_NAME=${TYPEORM_DATABASE}
    depends_on:
      - serasa-brain-ag-challenge-db
    env_file:
      - .env
    networks:
      - backend

  serasa-brain-ag-challenge-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:${TYPEORM_PORT}"
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge